#! /bin/bash

HADOOP=$(which hadoop)
HADOOP_INSTALL=$(dirname $(dirname $HADOOP))
HADOOP_CONF_DIR=${HADOOP_INSTALL}/conf

while read LINE
do
	rsync -avz ${HADOOP_CONF_DIR} ${LINE}:${HADOOP_CONF_DIR}
done < ${HADOOP_CONF_DIR}/slaves
