#! /bin/bash

PUB_FILE_PATH=${HOME}/.ssh/id_rsa.pub

if [ $1 == "--known" ]
then
	KNOWN_HOST=1
	shift 1
else
	KNOWN_HOST=0
fi

# help
if [ $# -ge 3 ]
then
	USERNAME=$1
	PASSWORD=$2
else
	echo "Usage: $0 (--known) {username} {password} {hostname}*"
	exit 1
fi

for HOSTNAME in ${@:3}
do
	if [ ${KNOWN_HOST} -eq 0 ]
	then
		# unknown host
		expect -c "
			spawn ssh-copy-id -i ${PUB_FILE_PATH} ${USERNAME}@${HOSTNAME}
			expect \"yes/no\"
			send \"yes\r\"
			expect \"password:\"
			send \"${PASSWORD}\r\"
			expect eof
		"
	else
		# known host
		expect -c "
			spawn ssh-copy-id -i ${PUB_FILE_PATH} ${USERNAME}@${HOSTNAME}
			expect \"password:\"
			send \"${PASSWORD}\r\"
			expect eof
		"
	fi
	
	ssh-keyscan -H ${HOSTNAME} >> ${HOME}/.ssh/known_hosts
done
